# Runs build and test
name: CI and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - name: Install svgexport
        run: npm install -g svgexport
      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick
      - name: Build site
        run: npm run build
      - name: Generate favicons
        run: |
          svgexport _site/favicon.svg _site/img/favicon/favicon-16x16.png 16:16
          svgexport _site/favicon.svg _site/img/favicon/favicon-32x32.png 32:32
          svgexport _site/favicon.svg _site/img/favicon/favicon-96x96.png 96:96
          svgexport _site/favicon.svg _site/img/favicon/favicon-192x192.png 192:192
          convert _site/img/favicon/favicon-16x16.png _site/img/favicon/favicon-32x32.png _site/img/favicon/favicon-96x96.png _site/img/favicon/favicon.ico
          svgexport _site/favicon.svg _site/img/favicon/apple-touch-icon.png 180:180
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
